# ============================================
# GitHub Workflow Automation Script
# Creates branches, PRs, issues, and simulates
# a full development workflow
# ============================================

# Configuration
$commitMessage = "Auto-generated commit"
$delaySeconds = 5  # Delay between full workflow iterations
$repoOwner = "your-username"      # CHANGE THIS
$repoName = "your-repo-name"      # CHANGE THIS

# Ensure gh CLI is authenticated
function Test-GitHubCLI {
    $ghAuth = gh auth status 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "GitHub CLI not authenticated. Run: gh auth login" -ForegroundColor Red
        exit 1
    }
    Write-Host "GitHub CLI authenticated ✓" -ForegroundColor Green
}

# Generate random branch name
function Get-RandomBranchName {
    $adjectives = @("feature", "bugfix", "hotfix", "release", "chore", "refactor", "update", "enhance")
    $nouns = @("module", "component", "handler", "service", "utils", "config", "api", "ui", "database", "cache")
    $verbs = @("fix", "add", "remove", "update", "implement", "optimize", "rework", "migrate")
    
    $adj = Get-Random $adjectives
    $noun = Get-Random $nouns
    $verb = Get-Random $verbs
    $id = Get-Random -Minimum 1000 -Maximum 9999
    
    return "$adj/$verb-$noun-$id"
}

# Generate random content
function Get-RandomContent {
    $contentTypes = @("code", "text", "json", "markdown", "yaml")
    $type = Get-Random $contentTypes
    
    switch ($type) {
        "code" {
            $funcName = "func_$(-join ((97..122) | Get-Random -Count 8 | ForEach-Object {[char]$_}))"
            return @"
// Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
// Branch: $(git branch --show-current 2>$null)

function $funcName() {
    const data = {
        id: $((Get-Random -Maximum 9999)),
        timestamp: Date.now(),
        value: $((Get-Random -Maximum 100))
    };
    
    console.log('Processing:', data);
    return data.value * $((Get-Random -Maximum 10));
}

module.exports = { $funcName };
"@
        }
        "text" {
            $lines = @()
            $lineCount = Get-Random -Minimum 5 -Maximum 15
            for ($i = 0; $i -lt $lineCount; $i++) {
                $randomWord = -join ((97..122) | Get-Random -Count (Get-Random -Minimum 5 -Maximum 12) | ForEach-Object {[char]$_})
                $lines += "[$i] Log entry: $randomWord - Status: $(Get-Random @('OK', 'PENDING', 'COMPLETE', 'SKIPPED'))"
            }
            return ($lines -join "`n")
        }
        "json" {
            return @"
{
    "metadata": {
        "generated": "$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss')",
        "branch": "$(git branch --show-current 2>$null)",
        "version": "1.$((Get-Random -Maximum 100)).$((Get-Random -Maximum 10))"
    },
    "data": {
        "id": $((Get-Random -Maximum 10000)),
        "type": "$(Get-Random @('user', 'system', 'event', 'metric'))",
        "payload": "$(-join ((65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object {[char]$_}))",
        "priority": $(Get-Random -Maximum 5)
    }
}
"@
        }
        "markdown" {
            return @"
# $(Get-Random @('Documentation', 'Changelog', 'Notes', 'Report')) - $(Get-Date -Format 'yyyy-MM-dd')

## Overview
Generated automatically for branch: \`$(git branch --show-current 2>$null)\`

## Details
- **ID**: $((Get-Random -Maximum 10000))
- **Status**: $(Get-Random @('Active', 'Draft', 'Review', 'Complete'))
- **Priority**: $(Get-Random -Maximum 5)/5

## Changes
$((1..(Get-Random -Minimum 2 -Maximum 6) | ForEach-Object { "- Item $_: $(-join ((97..122) | Get-Random -Count 8 | ForEach-Object {[char]$_}))" } | Join-String -Separator "`n"))

---
*Auto-generated by workflow script*
"@
        }
        "yaml" {
            return @"
# Configuration generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
version: '1.$((Get-Random -Maximum 100))'
environment: $(Get-Random @('development', 'staging', 'production'))

service:
  name: $(-join ((97..122) | Get-Random -Count 8 | ForEach-Object {[char]$_}))
  port: $((3000 + (Get-Random -Maximum 1000)))
  replicas: $(Get-Random -Minimum 1 -Maximum 5)

settings:
  debug: $(Get-Random @('true', 'false'))
  timeout: $(Get-Random -Minimum 10 -Maximum 60)
  retries: $(Get-Random -Minimum 1 -Maximum 5)
"@
        }
    }
}

# Generate random issue title and body
function Get-RandomIssue {
    $issueTypes = @("Bug", "Feature", "Task", "Refactor", "Documentation", "Test")
    $type = Get-Random $issueTypes
    
    $titles = @{
        "Bug" = @(
            "Fix memory leak in processing module",
            "Resolve race condition in async handler",
            "Fix null pointer exception in edge case",
            "Address performance degradation",
            "Fix incorrect error handling"
        )
        "Feature" = @(
            "Add support for new data format",
            "Implement caching mechanism",
            "Add user authentication flow",
            "Create new API endpoint",
            "Add logging improvements"
        )
        "Task" = @(
            "Update dependencies to latest versions",
            "Clean up deprecated code",
            "Optimize database queries",
            "Refactor configuration handling",
            "Improve error messages"
        )
        "Refactor" = @(
            "Restructure module architecture",
            "Extract common utilities",
            "Simplify complex logic",
            "Remove duplicate code",
            "Improve code organization"
        )
        "Documentation" = @(
            "Update API documentation",
            "Add code comments",
            "Create setup guide",
            "Document configuration options",
            "Add usage examples"
        )
        "Test" = @(
            "Add unit tests for core functions",
            "Increase test coverage",
            "Add integration tests",
            "Create test fixtures",
            "Fix flaky tests"
        )
    }
    
    $bodies = @(
        "This needs to be addressed to improve system stability.",
        "Required for upcoming release milestone.",
        "Part of the ongoing maintenance effort.",
        "Identified during code review.",
        "Addresses technical debt accumulation.",
        "Implements requested functionality.",
        "Fixes reported issue from monitoring."
    )
    
    $title = "[$(Get-Random -Maximum 9999)] $(Get-Random $titles[$type])"
    $body = "$(Get-Random $bodies)`n`n**Type**: $type`n**Priority**: $(Get-Random -Maximum 5)/5`n**Generated**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    
    return @{
        Title = $title
        Body = $body
        Type = $type
    }
}

# Create a new branch and switch to it
function New-FeatureBranch {
    $branchName = Get-RandomBranchName
    
    Write-Host "`n=== Creating New Branch ===" -ForegroundColor Cyan
    Write-Host "Branch name: $branchName" -ForegroundColor White
    
    # Fetch latest from main
    git fetch origin main 2>$null | Out-Null
    
    # Create and checkout new branch from main
    git checkout -b $branchName origin/main 2>&1 | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Created and switched to branch: $branchName" -ForegroundColor Green
        return $branchName
    } else {
        Write-Host "✗ Failed to create branch" -ForegroundColor Red
        return $null
    }
}

# Create file and commit
function New-Commit {
    param([string]$BranchName)
    
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $extension = Get-Random @(".txt", ".js", ".json", ".md", ".yml", ".log")
    $fileName = "auto-$timestamp$extension"
    
    Write-Host "`n=== Creating File ===" -ForegroundColor Cyan
    Write-Host "File: $fileName" -ForegroundColor White
    
    # Generate and write content
    $content = Get-RandomContent
    $content | Set-Content $fileName -Encoding UTF8
    
    # Git add and commit
    git add $fileName | Out-Null
    
    $msg = "$commitMessage [$BranchName] - $timestamp"
    git commit -m $msg 2>&1 | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Committed: $msg" -ForegroundColor Green
        return $fileName
    } else {
        Write-Host "✗ Commit failed" -ForegroundColor Red
        return $null
    }
}

# Push branch and create PR
function New-PullRequest {
    param([string]$BranchName)
    
    Write-Host "`n=== Pushing Branch ===" -ForegroundColor Cyan
    
    git push -u origin $BranchName 2>&1 | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Pushed branch: $branchName" -ForegroundColor Green
        
        # Create PR using gh CLI
        Write-Host "`n=== Creating Pull Request ===" -ForegroundColor Cyan
        
        $prTitle = "Auto PR: $BranchName - $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
        $prBody = "This pull request was automatically generated.`n`n**Branch**: $BranchName`n**Created**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`nPlease review and merge."
        
        $prUrl = gh pr create --title $prTitle --body $prBody --base main --head $BranchName 2>&1
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "✓ Created PR: $prUrl" -ForegroundColor Green
            return $prUrl
        } else {
            Write-Host "✗ PR creation failed (may already exist)" -ForegroundColor Yellow
            return $null
        }
    } else {
        Write-Host "✗ Push failed" -ForegroundColor Red
        return $null
    }
}

# Create GitHub issue
function New-GitHubIssue {
    param([string]$BranchName)
    
    Write-Host "`n=== Creating GitHub Issue ===" -ForegroundColor Cyan
    
    $issue = Get-RandomIssue
    
    # Create issue with label
    $label = switch ($issue.Type) {
        "Bug" { "bug" }
        "Feature" { "enhancement" }
        "Task" { "task" }
        "Refactor" { "refactor" }
        "Documentation" { "documentation" }
        "Test" { "testing" }
        default { "automated" }
    }
    
    $issueUrl = gh issue create --title $issue.Title --body $issue.Body --label $label 2>&1
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Created issue: $($issue.Title)" -ForegroundColor Green
        Write-Host "  URL: $issueUrl" -ForegroundColor Gray
        
        # Extract issue number from URL
        $issueNumber = $issueUrl.Split('/')[-1]
        
        return @{
            Number = $issueNumber
            Url = $issueUrl
            Title = $issue.Title
        }
    } else {
        Write-Host "✗ Issue creation failed" -ForegroundColor Red
        return $null
    }
}

# Close the issue
function Close-GitHubIssue {
    param([string]$IssueNumber)
    
    Write-Host "`n=== Closing Issue #$IssueNumber ===" -ForegroundColor Cyan
    
    gh issue close $IssueNumber --comment "Resolved in automated workflow. Closing as complete." 2>&1 | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Closed issue #$IssueNumber" -ForegroundColor Green
        return $true
    } else {
        Write-Host "✗ Failed to close issue" -ForegroundColor Red
        return $false
    }
}

# Create follow-up commit referencing the issue
function New-FollowUpCommit {
    param(
        [string]$BranchName,
        [string]$IssueNumber
    )
    
    Write-Host "`n=== Creating Follow-up Commit ===" -ForegroundColor Cyan
    
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $fileName = "fix-$IssueNumber-$timestamp.md"
    
    $content = @"
# Fix for Issue #$IssueNumber

**Status**: Resolved  
**Branch**: $BranchName  
**Timestamp**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## Resolution
This file documents the resolution of issue #$IssueNumber.

## Changes Made
- Applied automated fix
- Updated related components
- Verified functionality

---
*Auto-generated resolution document*
"@
    
    $content | Set-Content $fileName -Encoding UTF8
    git add $fileName | Out-Null
    
    $msg = "Fix #$IssueNumber - Resolution commit [$BranchName]"
    git commit -m $msg 2>&1 | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Created follow-up commit: $msg" -ForegroundColor Green
        
        # Push the new commit
        git push origin $BranchName 2>&1 | Out-Null
        Write-Host "✓ Pushed follow-up commit" -ForegroundColor Green
        
        return $fileName
    } else {
        Write-Host "✗ Follow-up commit failed" -ForegroundColor Red
        return $null
    }
}

# Merge the PR (optional - uncomment if you want auto-merge)
function Merge-PullRequest {
    param([string]$BranchName)
    
    Write-Host "`n=== Merging Pull Request ===" -ForegroundColor Cyan
    
    gh pr merge $BranchName --squash --delete-branch --subject "Auto-merge: $BranchName" 2>&1 | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ Merged and deleted branch: $BranchName" -ForegroundColor Green
        return $true
    } else {
        Write-Host "✗ Merge failed (may require manual review)" -ForegroundColor Yellow
        return $false
    }
}

# Main workflow
function Start-Workflow {
    $iteration = 0
    
    while ($true) {
        $iteration++
        Write-Host "`n========================================" -ForegroundColor Magenta
        Write-Host "  WORKFLOW ITERATION #$iteration" -ForegroundColor Magenta
        Write-Host "  $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Magenta
        Write-Host "========================================" -ForegroundColor Magenta
        
        try {
            # Step 1: Create new branch
            $branch = New-FeatureBranch
            if (-not $branch) { throw "Branch creation failed" }
            
            # Step 2: Create initial commit
            $file1 = New-Commit -BranchName $branch
            if (-not $file1) { throw "Initial commit failed" }
            
            # Step 3: Push and create PR
            $prUrl = New-PullRequest -BranchName $branch
            
            # Step 4: Create GitHub issue
            $issue = New-GitHubIssue -BranchName $branch
            if (-not $issue) { throw "Issue creation failed" }
            
            # Step 5: Close the issue
            $closed = Close-GitHubIssue -IssueNumber $issue.Number
            
            # Step 6: Create follow-up commit referencing the issue
            $file2 = New-FollowUpCommit -BranchName $branch -IssueNumber $issue.Number
            
            # Step 7: Optional - merge the PR
            # Uncomment the next line to enable auto-merge
            # $merged = Merge-PullRequest -BranchName $branch
            
            # Return to main branch for next iteration
            git checkout main 2>&1 | Out-Null
            
            Write-Host "`n========================================" -ForegroundColor Green
            Write-Host "  WORKFLOW COMPLETE ✓" -ForegroundColor Green
            Write-Host "  Branch: $branch" -ForegroundColor Green
            Write-Host "  Issue: #$($issue.Number)" -ForegroundColor Green
            Write-Host "========================================" -ForegroundColor Green
            
        } catch {
            Write-Host "`n========================================" -ForegroundColor Red
            Write-Host "  WORKFLOW ERROR ✗" -ForegroundColor Red
            Write-Host "  $($_.Exception.Message)" -ForegroundColor Red
            Write-Host "========================================" -ForegroundColor Red
            
            # Return to main branch on error
            git checkout main 2>&1 | Out-Null
        }
        
        # Wait before next iteration
        Write-Host "`nWaiting $delaySeconds seconds before next iteration..." -ForegroundColor Blue
        Start-Sleep -Seconds $delaySeconds
    }
}

# ============================================
# SCRIPT ENTRY POINT
# ============================================

Write-Host @"
========================================
  GITHUB WORKFLOW AUTOMATION
========================================

This script will:
  1. Create random feature branches
  2. Commit auto-generated files
  3. Create Pull Requests
  4. Create and close GitHub Issues
  5. Add follow-up commits

Requirements:
  - Git repository with GitHub remote
  - gh CLI installed and authenticated
  - Write access to repository

========================================
"@ -ForegroundColor Cyan

# Check GitHub CLI
Test-GitHubCLI

# Verify we're in a git repo
if (-not (git rev-parse --git-dir 2>$null)) {
    Write-Host "Error: Not a git repository" -ForegroundColor Red
    exit 1
}

# Check remote
$remote = git remote get-url origin 2>$null
if (-not $remote) {
    Write-Host "Error: No origin remote configured" -ForegroundColor Red
    exit 1}

Write-Host "Repository: $remote" -ForegroundColor Green
Write-Host "`nStarting workflow in 3 seconds..." -ForegroundColor Yellow
Start-Sleep -Seconds 3

# Start the endless workflow
Start-Workflow